### ISSUE TITLE
Error at reuse = true

### ISSUE THREAD

**Issue by sankar19** [jazzsaxmafia/Impainting#4]
I get this error when I tried to train.

bn1/moments/moments_1/mean/ExponentialMovingAverage/biased does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

It happens at 
adversarial_neg = model.build_adversarial(reconstruction, is_train, reuse=True)

Thanks.

**Comment by LeeRel1991** [comment]
I met the same error with tensorflow 0.12. And when I tried to use tensorflow 0.11, the problem was solved. Good luck.

**Comment by sankar19** [comment]
Yes the error I guess is because in new tensor flow, by default, if reuse=True is specified, it will show error for variables that haven't been create in this case some parameters for batch normalization.  I simply removed batch normalization for adversarial network to work with new version.

**Comment by smhoang** [comment]
Thanks, it works with 0.12 after removing batch normalization for adversarial network. Is there any different results if we remove (and not remove) batch normalization ?

**Comment by hhwhbf** [comment]
@sankar19 Hi ,I met same problem when I tried to use tensorflow 1.0.1. Can you tell me how do you remove batch normalization for adversarial? Is it convenient for you to share your codes? Thank you very much!

**Comment by sankar19** [comment]
bn1 = self.leaky_relu(self.batchnorm(conv1, is_train, name='bn1'))
becomes
bn1 = self.leaky_reluconv1)

( self.batchnorm(conv1, is_train, name='bn1') --> conv1 ) in the adversarial code.

**Comment by hhwhbf** [comment]
OK，thank you very much ,so that your model based on this code has been trained?Is it a model that only contain L2 loss? @sankar19

**Comment by hhwhbf** [comment]
By the way, I met this error when I run the code.

Traceback (most recent call last):
  File "/home/hhw/PycharmProjects/untitled/train.imagenet.py", line 98, in <module>
    grads_vars_G = map(lambda gv: [tf.clip_by_value(gv[0], -10., 10.), gv[1]], grads_vars_G)
  File "/home/hhw/PycharmProjects/untitled/train.imagenet.py", line 98, in <lambda>
    grads_vars_G = map(lambda gv: [tf.clip_by_value(gv[0], -10., 10.), gv[1]], grads_vars_G)
  File "/home/hhw/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/clip_ops.py", line 53, in clip_by_value
    t = ops.convert_to_tensor(t, name="t")
  File "/home/hhw/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 620, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/hhw/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/constant_op.py", line 179, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/hhw/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/constant_op.py", line 162, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape))
  File "/home/hhw/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 346, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.

Python version:2.7.12   Tensorflow version:0.9.0
Is it a problem about tensorflow version?

**Comment by ghazi-f** [comment]
@hhwhbf See this other issue : #6 
@sankar19 you can go around that error by assigning False to reuse in an inner loop : 
`with tf.variable_scope(tf.get_variable_scope(), reuse=False):
                ema_apply_op = ema.apply([batch_mean, batch_var])`

**Comment by hhwhbf** [comment]
@Sora77 Excuse me,I have taken your suggestion in issue:#6,but there is still an error like this:
```
  File "C:/Users/Administrator/PycharmProjects/untitled1/train.imagenet.py", line 105, in <module>
    train_op_G = optimizer_G.apply_gradients( grads_vars_G )
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\tensorflow\python\training\optimizer.py", line 380, in apply_gradients
    raise ValueError("No variables provided.")
ValueError: No variables provided.
```
I use python3.5 and tensorflow 1.0.1.
Therefore,I guess that there is a difference between python3.5 and python2.7 which cause this error.
I am so glad if you can help to solve this problem,thank you.

**Comment by ghazi-f** [comment]
Hi, your error is in fact due to that difference. The fact is that the map() function yielding grads_vars_G returns a generator and not a list. So you just have to wrap it into a list () to cast a list out of it. 
I hope it resolves your issue.

**Comment by hhwhbf** [comment]
@Sora77 Yes,I have noticed that difference.So,I have changed my code.
```
 optimizer_G = tf.train.AdamOptimizer( learning_rate=learning_rate )
grads_vars_G = optimizer_G.compute_gradients( loss_G, var_list=var_G )
grads_vars_G = list(map(lambda gv: gv if gv[0] is None else [tf.clip_by_value(gv[0], -10., 10.), gv[1]],           grads_vars_G))
train_op_G = optimizer_G.apply_gradients( grads_vars_G )
```
It is strange that there still an error above.Latter,I have found that not only map() function need wrap list() but also filter() function need.
```
var_G = list(filter( lambda x: x.name.startswith('GEN'), tf.trainable_variables()))
var_D = list(filter( lambda x: x.name.startswith('DIS'), tf.trainable_variables()))

W_G = list(filter(lambda x: x.name.endswith('W:0'), var_G))
W_D = list(filter(lambda x: x.name.endswith('W:0'), var_D))
```
Now the problem have been solved,thank you very much.
