### ISSUE TITLE
Unused channel wise full connection

### ISSUE THREAD

**Issue by ghazi-f** [jazzsaxmafia/Impainting#7]
Hi,
Thanks a lot for your implementation  ! I can see you have your channel wise fully connected layer function in your Model.py but you're not using it in building your generator. 
Can I know why ?

**Comment by Tmn07** [comment]
Hi, you can find it in context encoder's paper Supplementary Material.
they use 4000 units' bottleneck layer instead of channel-wise FC.

**Comment by ghazi-f** [comment]
Thanks a lot ! I didn't notice it. I'm closing this issue.
This may not be the right place to ask this, but please allow me : Did you understand why it was removed in the inpainting implementation (and kept in the feature learning one) ? Was it a purely empirical decision ?

**Comment by Tmn07** [comment]
https://github.com/pathak22/context-encoder/issues/10
that maybe help you : )

**Comment by ghazi-f** [comment]
He says it is simply not required ... well Ok.
Thank you for the fast answer @qq519043202  !
